---
debug: false
logs:
  level: INFO
  token: ~
mongodb:
  port: 27020
  database: catalog
  host: catalog.sd2e.org
  username: catalog
  password: ~
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
skip_prefixes:
  - .placeholder
